### ISSUE TITLE
gitlab version update 11.x

### ISSUE THREAD

**Issue by csonuryilmaz** [cmarquardt/docker-gitlab-ee-subgit#1]
Hi, first of all thanks for your docker file. 

It eased my jobs and gained me a lot of time about subgit & gitlab integration. I'm a newbie on Docker. So I don't understand a point:

Docker file contains `FROM gitlab/gitlab-ee:latest` line bu when I run container (after installation) I've detected Gitlab's version as `10.8.1-ee`. I was expecting the latest version of Gitlab which is 11.6+ nowadays. 

I've read the `README.md` file from this repository. Is below section from the file
> ... I handle versioned tags manually, based on officially tagged images as available in the Official GitLab repository. Should I forget to update, please raise a ticket at github. ...

referring to this situation? If yes, how can update to more recent versions of Gitlab? Also, I've installed some `svn` repos and now they're in sync with `subgit`. If I upgrade the Gitlab version with a new docker file, is there any possibility that this upgrade break down my installed repos and `subgit` configuration?

**Comment by cmarquardt** [comment]
Hi,

thanks for making me aware - the builds that generated the `:latest` image had failed for a some (significant) time because the SubGit version I used in the Dockerfile wasn't offered under the original download link any more. The SubGit in the Docker image also was quite outdated. I've fixed both issues, and the the `:latest` image should now be up-to-date again - with respect to both GitLab and SubGit. 

So indeed the statement you refer to is indeed referring to a situation like this one; the Dockerfile for the automated build of the `:latest` image just didn't work correctly any more, and I hadn't fixed that. My apologies!

On your other questions: To start with, the idea of the Docker image is that you run it with external volumes (see the `README.md` file on which ones are exported); all data that you'd like to keep independent from any particular GitLab version is stored on them, but not in the container that is created from the Docker image. That includes your repositories, but also configurations files, the GitLab database, license keys for SubGit, etc. In principle, a software update then works by downloading a new Docker image, replacing the old version with the new one in your `docker-compose.yml` file (or the script that runs Docker from the command line). Once you run the new image, the previous Docker container is replaced with a new one containing the new version of GitLab, but still using the existing data. 

So, *if* you have all data (including repositories, configurations files etc.) stored on external volumes (that is, *not* only in the Docker container), you've got a very simple way to do software upgrades, which is why Docker is so great;-) 

However: Especially between major version releases, GitLab's database structure changes - keep in mind that it doesn't matter if you do a manual upgrade of the GitLab server, or if you download and use a Docker image with a new version. Usually, when starting up, GitLab checks the version of the database and performs any necessary upgrades automatically. If that automatic upgrade works fine, you'll simply start using the new GitLab version and all is good. But if it doesn't, you'll be stuck with a potentially inconsistent state of of the GitLab database. That is why you want a backup: to roll back any changes to the GitLab data, and also to use the previous Docker image again, just in case something goes wrong with GitLab's internal upgrade mechanism.

So in summary - updating the Docker image *shouldn't* break your repositories as long as GitLab's version upgrade scheme works flawlessly. The same applies to the SubGit configuration. In any case, if you want to have backups - of both your data and the previous Docker image. 

A potential problem with the `:latest` image is that it is overwritten whenever a new version of it is generated; so you won't be able to download a previous version, say from Docker Hub. That is why I used to maintain additional versions of the image with specific GitLab versions. As I actually don't use these images myself any more (we finally migrated all SVN repositories to git, so we lost the need for SubGit), I stopped doing those manual updates of the Docker images, though. 

Would it help you if I continue to maintain these tagged versions? I can't offer any testing, though...

**Comment by csonuryilmaz** [comment]
Hi, thanks for the quick and detailed comment. :blush: Also, for quick fixes! :+1: 

After reading your detailed explanation, I checked your modifications on `github` and `docker hub`. I understood the situation. The last successful build on `docker hub` was 8 months ago and I used that build, for this reason my installed `gitlab` version is `10.8.1-ee` which was released on `2018/05/24`.

> So in summary - updating the Docker image shouldn't break your repositories as long as GitLab's version upgrade scheme works flawlessly. The same applies to the SubGit configuration. In any case, if you want to have backups - of both your data and the previous Docker image.

Ok, I got the idea. Before updating the image, I'll have a full backup of machine (aside from data) for any possible failure (data corruption vs.). By this way, on any error I can go back to my old full backup quickly and continue with it without much effort. It took me about ~2-3 days to making `gitlab` and `subgit` ready and developers are now using it. So I've to upgrade carefully.

> Would it help you if I continue to maintain these tagged versions? I can't offer any testing, though...

I think, it'll be helpful to us. Because from `gitlab` version 10.8, you can't skip major versions when upgrading. Here is the related section from [documentation:](https://docs.gitlab.com/omnibus/update/) 

> From version 10.8 onwards, upgrade paths are enforced for version upgrades by default. This restricts performing direct upgrades that skip major versions (for example 10.3 to 12.7 in one jump) which can result in breakage of the GitLab installations due to multiple reasons like deprecated or removed configuration settings, upgrade of internal tools and libraries etc.

So tagged versions may help us on step by step upgrade without skipping major versions.
And at any time (when an upgrade break something, or when our data isn't compatible with new version) we can go back to an old but working tag.

**Comment by cmarquardt** [comment]
Yes, that seems to be right. Especially the need for properly tagged versions to perform upgrades... thanks for the link!

So by now, Docker Hub has an image for each official GitLab Docker image. You should be able to first replace the `:latest` image you're currently using with the corresponding tagged one (`10.8.1-ee.0` I would think); this shouldn't trigger any changes apart from the transition from SubGit v3.2.5 to SubGit v3.3.5. Once that works fine, you should be able to upgrade the Gitlab versions up to the most recent 11.6, through many little steps.

I apologise for causing you so much trouble - and especially for you having to perform all these individual upgrade steps now in order to get your Gitlab to an up-to-date version. At least I finally sat down and wrote a reasonably automated upgrader for the images... I'm still testing it, but in a few days from now there should be a daily check if new Gitlab images are available, and if so, the corresponding versions with SubGit should be created automatically.

Could you let me know if that upgrade path (and the new images) work for you? And once more my apologies!

   Christian.

**Comment by csonuryilmaz** [comment]
> So by now, Docker Hub has an image for each official GitLab Docker image.

I took a look at your awesome job on `github` and `dockerhub` and I'm glad to see new tagged images.
> ... this shouldn't trigger any changes apart from the transition from SubGit v3.2.5 to SubGit v3.3.5. Once that works fine, you should be able to upgrade the Gitlab versions up to the most recent 11.6, through many little steps. ...

This seems to be a good and seamless starting point for an upgrade.
> ... I apologise for causing you so much trouble - and especially for you having to perform all these individual upgrade steps ...

By now, not a serious problem for us. For now, developers have no complaints about `gitlab` version. They are currently happy with `gitlab` and `subgit` integration. On the other hand I'm looking at release notes of `gitlab`. If we hit a bug or need a new important feature which is implemented on later versions (10.8+) of `gitlab`, we'll start an upgrade process. By now, in terms of preparation, I'm planning to try an upgrade on a brand new replica server and check the results in my spare time.
> ... At least I finally sat down and wrote a reasonably automated upgrader for the images... I'm still testing it, but in a few days from now there should be a daily check if new Gitlab images are available, and if so, the corresponding versions with SubGit should be created automatically.

I'm closing the issue because now we have tagged images and you helped us!
Thanks a lot for your awesome work and help. :+1: 
This was my first `docker` experience and I 've learned a lot from this conversation. :blush:

**Comment by cmarquardt** [comment]
Great - I'm glad I could help. And thanks for your nice words!
